[pytest]
asyncio_mode = auto
pythonpath = "."
testpaths = tests
addopts = '-p no:warnings' --cov=galeria --cov-report=term-missing --cov-branch
norecursedirs = 
    .* 
    build 
    dist 
    galeria/_examples
markers =
    debug: testes visuais ou auxiliares de debugging