from .config import (
    ANIMATE_OPACITY,
    APP_TITLE,
    AUTO_TIME_VIEW_BACK,
    DETAIL_TIMEOUT_SECONDS,
    FADE_OUT_ASYNC_SLEEP,
    SCROLL_DURATION,
    SCROLL_RESET_DURATION,
)
from .paths import ASSETS_DIR, BASE_DIR, DATA_DIR, LOGO_DETIC, LOGO_UNICAMP, PHOTOS_DIR, SUPERS_JSON

__all__ = [
    "ANIMATE_OPACITY",
    "APP_TITLE",
    "ASSETS_DIR",
    "AUTO_TIME_VIEW_BACK",
    "BASE_DIR",
    "DATA_DIR",
    "DETAIL_TIMEOUT_SECONDS",
    "FADE_OUT_ASYNC_SLEEP",
    "LOGO_DETIC",
    "LOGO_UNICAMP",
    "PHOTOS_DIR",
    "SCROLL_DURATION",
    "SCROLL_RESET_DURATION",
    "SUPERS_JSON",
]
