# galeria/domain/protocols/gallery_service_like.py
"""Protocolo do serviço consumido pela visão de galeria."""

from collections.abc import Sequence
from typing import Protocol

from galeria.domain import Era, Super


class GalleryServiceLike(Protocol):
    """Contrato necessário para listar e abrir itens na galeria."""

    def listar_supers(self) -> Sequence[Super]: ...
    def listar_eras(self) -> Sequence[Era]: ...
    def obter_era(self, era_id: str) -> Era | None: ...
    def obter_theme_da_era(self, era_id: str) -> str | None: ...
    def pode_abrir(self, super_data: Super) -> bool: ...
    def build_image_path(self, super_data: Super) -> str | None: ...
    def build_timeline_path(self, super_data: Super) -> str | None: ...
