# domain/protocols/gallery_service_like.py

from collections.abc import Sequence
from pathlib import Path
from typing import Protocol

from galeria.domain import Era, Super


class GalleryServiceLike(Protocol):
    def listar_supers(self) -> Sequence[Super]: ...
    def listar_eras(self) -> Sequence[Era]: ...
    def obter_era(self, era_id: str) -> Era | None: ...
    def obter_theme_da_era(self, era_id: str) -> str | None: ...
    def pode_abrir(self, super_data: Super) -> bool: ...
    def build_image_path(self, super_data: Super) -> Path | None: ...
    def build_timeline_path(self, super_data: Super) -> Path | None: ...
