# domain/protocols/super_service_like.py

from collections.abc import Sequence
from pathlib import Path
from typing import Protocol

from galeria.domain import Era, Super


class SuperServiceLike(Protocol):
    # leitura
    def listar_supers(self) -> Sequence[Super]: ...
    def listar_eras(self) -> Sequence[Era]: ...
    def obter_era(self, era_id: str) -> Era | None: ...
    def obter_theme_da_era(self, era_id: str) -> str | None: ...

    # def listar_supers_visiveis(self) -> list[Super]: ...
    # def obter_super(self, super_id: str) -> Super | None: ...

    # regras de domínio
    def is_blank(self, super_data: Super) -> bool: ...
    def pode_abrir(self, super_data: Super) -> bool: ...

    # helpers para UI
    def build_image_path(self, super_data: Super) -> Path | None: ...
    def build_timeline_path(self, super_data: Super) -> Path | None: ...
