from collections.abc import Callable
from typing import Protocol

from galeria.domain.protocols.theme_like import ThemeLike


class ThemeManagerLike(Protocol):
    @property
    def theme(self) -> ThemeLike: ...

    @property
    def accent(self) -> object: ...

    @property
    def gallery(self) -> object: ...

    @property
    def header(self) -> object: ...

    @property
    def image(self) -> object: ...

    @property
    def logo(self) -> object: ...

    @property
    def super_detail(self) -> object: ...

    @property
    def base(self) -> object: ...

    @property
    def button(self) -> object: ...

    @property
    def colors(self) -> object: ...

    @property
    def spacing(self) -> object: ...

    @property
    def radius(self) -> object: ...

    @property
    def typography(self) -> object: ...

    @property
    def text(self) -> object: ...

    @property
    def timeline(self) -> object: ...

    @property
    def ui(self) -> object: ...

    def set_theme(self, theme: ThemeLike) -> None: ...

    def set_theme_for_era(self, era_id: str | None) -> None: ...

    def get_theme_for_era(self, era_id: str | None) -> ThemeLike: ...

    def subscribe(self, listener: Callable) -> None: ...

    def unsubscribe(self, listener: Callable) -> None: ...
